services:
  alfresco:
    image: alfresco/alfresco-content-repository-community:6.2.1-A2
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - solr6
      - activemq
      - transform-core-aio
      - ocr-transformer
    environment:
      JAVA_OPTS: >
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=${POSTGRES_USER:-alfresco}
        -Ddb.password=${POSTGRES_PASSWORD:-alfresco}
        -Ddb.url=jdbc:postgresql://postgres:5432/${POSTGRES_DB:-alfresco}
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.secureComms=none
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Ddeployment.method=DOCKER_COMPOSE
        -Dcsrf.filter.enabled=false
        -XX:+UseG1GC -XX:+UseStringDeduplication
        -Xmx${ALFRESCO_XMX:-2g} -Xms${ALFRESCO_XMS:-1g}
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Dlocal.transform.service.enabled=true
        -Dalfresco-pdf-renderer.url=http://transform-core-aio:8090/
        -Djodconverter.url=http://transform-core-aio:8090/
        -Dimg.url=http://transform-core-aio:8090/
        -Dtika.url=http://transform-core-aio:8090/
        -Dtransform.misc.url=http://transform-core-aio:8090/
        -DlocalTransform.ocr.url=http://ocr-transformer:8090/
    volumes:
      - ./volumes/data/alf-repo-data:/usr/local/tomcat/alf_data
      - ./volumes/logs/alfresco:/usr/local/tomcat/logs
      # Mount the whole classes dir; put alfresco-global.properties inside ./volumes/config/classes/
      - ./volumes/config/classes:/usr/local/tomcat/shared/classes
    networks:
      - internal

  share:
    image: alfresco/alfresco-share:6.2.1
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - alfresco
    environment:
      - REPO_HOST=alfresco
      - REPO_PORT=8080
      - CATALINA_OPTS=-XX:+UseG1GC -XX:+UseStringDeduplication -Xms${SHARE_XMS:-256m} -Xmx${SHARE_XMX:-512m}
    volumes:
      - ./volumes/logs/share:/usr/local/tomcat/logs
      - ./volumes/config/ext-share-config-custom.xml:/usr/local/tomcat/shared/classes/alfresco/web-extension/ext-share-config-custom.xml
    networks:
      - internal

  solr6:
    image: alfresco/alfresco-search-services:1.2.0
    restart: always
    ports:
      - 8983:8983
    environment:
      SOLR_ALFRESCO_HOST: alfresco
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: solr6
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      SOLR_JAVA_MEM: "-Xms1g -Xmx2g"
      ALFRESCO_SECURE_COMMS: "none"
    volumes:
      - ./volumes/data/solr-data:/opt/alfresco-search-services/data
    networks:
      - internal

  content-app:
    image: alfresco/alfresco-content-app:master
    restart: always
    ports:
      - 8070:8070
    depends_on:
      - alfresco
    environment:
      - BASEPATH=aca
    networks:
      - internal

  postgres:
    image: postgres:11.7
    restart: always
    networks:
      - internal
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-alfresco}
      - POSTGRES_USER=${POSTGRES_USER:-alfresco}
      - POSTGRES_DB=${POSTGRES_DB:-alfresco}
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    volumes:
      - ./volumes/data/postgres-data:/var/lib/postgresql/data
      - ./volumes/logs/postgres:/var/log/postgresql
    ports:
      - 5432:5432

  proxy:
    image: nginx:stable-alpine
    restart: always
    depends_on:
      - content-app
      - share
    volumes:
      - ./volumes/config:/etc/nginx/conf.d
      - ./volumes/logs/nginx:/var/log/nginx
    networks:
      - internal
    ports:
      - 9090:80

  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:2.3.2
    restart: always
    networks:
      - internal
    deploy:
      resources:
        limits:
          memory: 1536M
    environment:
      JAVA_OPTS: " -Xms256m -Xmx1536m"
    ports:
      - 8090:8090

  ocr-transformer:
    image: ketan32/karnataka-bank:ocr-app
    restart: always
    networks:
      - internal
    environment:
      JAVA_OPTS: " -XX:MinRAMPercentage=50 -XX:MaxRAMPercentage=80"
      # Example OCR flags:
      # OCRMYPDF_ARGUMENTS=--skip-text -l eng
    ports:
      - 8091:8090

  activemq:
    image: alfresco/alfresco-activemq:5.15.8
    restart: always
    networks:
      - internal
    ports:
      - 8161:8161   # Web Console
      - 5672:5672   # AMQP
      - 61616:61616 # OpenWire
      - 61613:61613 # STOMP

networks:
  internal:
